import type { PlanProfile } from '../types';

export const DEMO_UNINSURED: Partial<PlanProfile> = {
  entryPath: 'diagnosed',
  ageBand: '50_54',
  sexAtBirth: 'female',
  smokingHistory: 'never',
  familyHistory: ['breast_ovarian'],
  hasPrimaryCare: 'no',
  cancerType: 'breast',
  stage: 'II',
  carePhase: 'just_diagnosed',
  treatments: ['surgery', 'chemo'],
  hasNavigator: 'no',
  priorities: ['cost', 'understanding', 'what_to_ask'],
  insuranceType: 'none',
  employment: 'full_time',
  employerSize: 'under50',
  tenureOver12mo: 'yes',
  paidLeave: 'limited',
  transport: 'own_car',
  travelTimeBand: '30_60',
  caregiver: 'nearby',
  dependentsAtHome: 'children',
};

export const DEMO_UNCAPPED_MEDICARE: Partial<PlanProfile> = {
  entryPath: 'diagnosed',
  ageBand: '65_74',
  sexAtBirth: 'male',
  smokingHistory: 'former',
  packYearsBand: '20_30',
  familyHistory: ['lung'],
  hasPrimaryCare: 'yes',
  cancerType: 'lung',
  stage: 'III',
  carePhase: 'in_treatment',
  treatments: ['chemo', 'radiation'],
  hasNavigator: 'yes',
  priorities: ['cost', 'side_effects', 'understanding'],
  insuranceType: 'medicare_original',
  hasMedigap: 'no',
  hasPartD: 'yes',
  deductibleRemaining: 'met',
  oopSpentBand: '2k_5k',
  facilityType: 'academic',
  networkChecked: 'yes',
  drugRoute: ['infused', 'oral'],
  billsInCollections: 'no',
  wantsAssistanceCheck: true,
  householdSize: 2,
  fplBand: '250_400',
  employment: 'retired',
  transport: 'someone_drives',
  travelTimeBand: '60_120',
  caregiver: 'lives_with',
  dependentsAtHome: 'none',
};
