export interface ParishData {
  name: string;
  slug: string;
  classification: 'rural' | 'urban' | null;
  hpsa: boolean | null;
}

export const PARISH_DATA: ParishData[] = [
  { slug: "acadia", name: "Acadia", classification: "urban", hpsa: true },
  { slug: "allen", name: "Allen", classification: "rural", hpsa: true },
  { slug: "ascension", name: "Ascension", classification: "urban", hpsa: false },
  { slug: "assumption", name: "Assumption", classification: "rural", hpsa: true },
  { slug: "avoyelles", name: "Avoyelles", classification: "rural", hpsa: true },
  { slug: "beauregard", name: "Beauregard", classification: "rural", hpsa: true },
  { slug: "bienville", name: "Bienville", classification: "rural", hpsa: true },
  { slug: "bossier", name: "Bossier", classification: "urban", hpsa: false },
  { slug: "caddo", name: "Caddo", classification: "urban", hpsa: true },
  { slug: "calcasieu", name: "Calcasieu", classification: "urban", hpsa: false },
  { slug: "caldwell", name: "Caldwell", classification: "rural", hpsa: true },
  { slug: "cameron", name: "Cameron", classification: "urban", hpsa: true },
  { slug: "catahoula", name: "Catahoula", classification: "rural", hpsa: true },
  { slug: "claiborne", name: "Claiborne", classification: "rural", hpsa: true },
  { slug: "concordia", name: "Concordia", classification: "rural", hpsa: true },
  { slug: "desoto", name: "De Soto", classification: "urban", hpsa: true },
  { slug: "east-baton-rouge", name: "East Baton Rouge", classification: "urban", hpsa: true },
  { slug: "east-carroll", name: "East Carroll", classification: "rural", hpsa: true },
  { slug: "east-feliciana", name: "East Feliciana", classification: "urban", hpsa: true },
  { slug: "evangeline", name: "Evangeline", classification: "rural", hpsa: true },
  { slug: "franklin", name: "Franklin", classification: "rural", hpsa: true },
  { slug: "grant", name: "Grant", classification: "rural", hpsa: true },
  { slug: "iberia", name: "Iberia", classification: "rural", hpsa: true },
  { slug: "iberville", name: "Iberville", classification: "urban", hpsa: true },
  { slug: "jackson", name: "Jackson", classification: "rural", hpsa: true },
  { slug: "jefferson", name: "Jefferson", classification: "urban", hpsa: false },
  { slug: "jefferson-davis", name: "Jefferson Davis", classification: "rural", hpsa: true },
  { slug: "lafayette", name: "Lafayette", classification: "urban", hpsa: false },
  { slug: "lafourche", name: "Lafourche", classification: "urban", hpsa: true },
  { slug: "lasalle", name: "La Salle", classification: "rural", hpsa: true },
  { slug: "lincoln", name: "Lincoln", classification: "rural", hpsa: true },
  { slug: "livingston", name: "Livingston", classification: "urban", hpsa: false },
  { slug: "madison", name: "Madison", classification: "rural", hpsa: true },
  { slug: "morehouse", name: "Morehouse", classification: "rural", hpsa: true },
  { slug: "natchitoches", name: "Natchitoches", classification: "rural", hpsa: true },
  { slug: "orleans", name: "Orleans", classification: "urban", hpsa: true },
  { slug: "ouachita", name: "Ouachita", classification: "urban", hpsa: true },
  { slug: "plaquemines", name: "Plaquemines", classification: "urban", hpsa: true },
  { slug: "pointe-coupee", name: "Pointe Coupee", classification: "urban", hpsa: true },
  { slug: "rapides", name: "Rapides", classification: "urban", hpsa: true },
  { slug: "red-river", name: "Red River", classification: "rural", hpsa: true },
  { slug: "richland", name: "Richland", classification: "rural", hpsa: true },
  { slug: "sabine", name: "Sabine", classification: "rural", hpsa: true },
  { slug: "st-bernard", name: "St. Bernard", classification: "urban", hpsa: true },
  { slug: "st-charles", name: "St. Charles", classification: "urban", hpsa: false },
  { slug: "st-helena", name: "St. Helena", classification: "urban", hpsa: true },
  { slug: "st-james", name: "St. James", classification: "urban", hpsa: false },
  { slug: "st-john-the-baptist", name: "St. John the Baptist", classification: "urban", hpsa: true },
  { slug: "st-landry", name: "St. Landry", classification: "rural", hpsa: true },
  { slug: "st-martin", name: "St. Martin", classification: "urban", hpsa: true },
  { slug: "st-mary", name: "St. Mary", classification: "rural", hpsa: true },
  { slug: "st-tammany", name: "St. Tammany", classification: "urban", hpsa: false },
  { slug: "tangipahoa", name: "Tangipahoa", classification: "urban", hpsa: true },
  { slug: "tensas", name: "Tensas", classification: "rural", hpsa: true },
  { slug: "terrebonne", name: "Terrebonne", classification: "urban", hpsa: true },
  { slug: "union", name: "Union", classification: "urban", hpsa: true },
  { slug: "vermilion", name: "Vermilion", classification: "urban", hpsa: true },
  { slug: "vernon", name: "Vernon", classification: "rural", hpsa: true },
  { slug: "washington", name: "Washington", classification: "rural", hpsa: true },
  { slug: "webster", name: "Webster", classification: "rural", hpsa: true },
  { slug: "west-baton-rouge", name: "West Baton Rouge", classification: "urban", hpsa: false },
  { slug: "west-carroll", name: "West Carroll", classification: "rural", hpsa: true },
  { slug: "west-feliciana", name: "West Feliciana", classification: "urban", hpsa: true },
  { slug: "winn", name: "Winn", classification: "rural", hpsa: true }
];
